"use client";

import { motion } from "framer-motion";
import { MapPin, Clock } from "lucide-react";
import { GeneratedBrief, IntakeFormData } from "@/types";
import HeroSection from "@/components/preview/HeroSection";
import AboutSection from "@/components/preview/AboutSection";
import MenuHighlight from "@/components/preview/MenuHighlight";
import SectionsPreview from "@/components/preview/SectionsPreview";
import PaletteStrip from "@/components/preview/PaletteStrip";
import BookingOverlay from "@/components/preview/BookingOverlay";

interface PreviewClientProps {
  formData: IntakeFormData;
  brief: GeneratedBrief;
}

export default function PreviewClient({
  formData,
  brief,
}: PreviewClientProps) {
  const primaryColor = brief.colorPalette[0]?.hex || "#E44332";

  return (
    <div className="min-h-screen bg-white">
      {/* Preview banner */}
      <motion.div
        initial={{ y: -40 }}
        animate={{ y: 0 }}
        className="bg-gray-900 text-white text-center py-2.5 px-4 text-sm"
      >
        <span className="text-gray-400">This is a draft preview for </span>
        <span className="font-semibold">{formData.restaurantName}</span>
        <span className="text-gray-400">
          {" "}
          — crafted by{" "}
        </span>
        <span className="text-primary font-medium">magical.</span>
      </motion.div>

      {/* Mock site header */}
      <header className="px-6 py-4 border-b border-gray-50">
        <div className="max-w-4xl mx-auto flex items-center justify-between">
          <span
            className="text-xl font-bold tracking-tight"
            style={{ color: primaryColor }}
          >
            {formData.restaurantName}
          </span>
          <div className="hidden md:flex items-center gap-6 text-sm text-gray-400">
            <span className="flex items-center gap-1.5">
              <MapPin size={14} />
              {formData.location}
            </span>
            <span className="flex items-center gap-1.5">
              <Clock size={14} />
              {formData.hours}
            </span>
          </div>
        </div>
      </header>

      {/* Generated sections */}
      <HeroSection brief={brief} formData={formData} />
      <PaletteStrip brief={brief} />
      <AboutSection brief={brief} />
      <MenuHighlight brief={brief} formData={formData} />
      <SectionsPreview brief={brief} />

      {/* Footer */}
      <footer className="py-12 px-6 border-t border-gray-100">
        <div className="max-w-4xl mx-auto text-center">
          <p className="text-sm text-gray-300 mb-2">
            {formData.restaurantName} &mdash; {formData.location}
          </p>
          <p className="text-xs text-gray-200">
            Website concept generated by magical.
          </p>
        </div>
      </footer>

      {/* Booking overlay */}
      <BookingOverlay />
    </div>
  );
}
